spring:
  profiles:
    active:
    - dev #当前使用环境
---
content: dev content 刷新出来看看
spring:
  profiles: dev
  application:
    name: manage-brand-provider
eureka:
  client:
    service-url:
      defaultZone: http://yys.server1.com:1001/eureka/
---
content: test content 刷新出来看看
spring:
  profiles: test
  application:
    name: manage-brand-provider
